export const WEBSITE_HOME = '/'
export const WEBSITE_ABOUT = '/about'
export const WEBSITE_SERVICES = '/services'
export const WEBSITE_PROJECTS = '/projects'
export const WEBSITE_FAQS = '/faqs'
export const WEBSITE_CONTACT = '/contact'
