import { Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const CormorantFont=Cormorant_Garamond({
  weight:['400','500','600','700',],
  subsets:["latin"],
  display :"swap"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${CormorantFont.className}  antialiased `}
      >
       <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
